
export const TAB_TOUT          = '__tout__'
export const TAB_A_RECEVOIR    = '__a_recevoir__'
export const TAB_A_ENVOYER     = '__a_envoyer__'
export const TAB_A_ENVOYER_LOT = '__a_envoyer_lot__'
export const TAB_ENVOYES          = '__envoyes__'
export const TAB_COMPTES_VINTED   = '__comptes_vinted__'
export const TAB_WORKSPACE        = '__workspace__'
export const TAB_EMPLOYEES        = '__employees__'
export const TAB_FONDS            = '__fonds__'
export const TAB_CONNEXIONS       = '__connexions__'
